name: "Manage Fabric Workspaces"

on:
  push:
    branches:
      - main

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  create-workspaces:
    runs-on: ubuntu-latest
    steps:
      - name: Run Fabric CLI
        uses: StevenBuglione/fabric-cli-action@latest
        with:
          resource_type: "workspace"
          action: "create"
          value: "${{ github.run_id }}"

  list-workspaces:
    needs: create-workspaces
    runs-on: ubuntu-latest
    steps:
      - name: Run Fabric CLI
        uses: StevenBuglione/fabric-cli-action@latest
        with:
          resource_type: "workspace"
          action: "list"