name: "Manage Fabric Workspaces"

on:
  push:
    branches:
      - 2.0.0

env:
  AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
  AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}

jobs:
  create-workspaces:
    runs-on: ubuntu-latest
    steps:
      - name: Run Fabric CLI
        uses: StevenBuglione/fabric-cli-action@v3.0
        with:
          resource_type: "workspace"
          action: "create"
          value: "${{ github.run_id }}"

  list-workspaces:
    needs: create-workspaces
    runs-on: ubuntu-latest
    steps:
      - name: Run Fabric CLI
        uses: StevenBuglione/fabric-cli-action@v3.0
        with:
          resource_type: "workspace"
          action: "list"
